[font.normal]
family = "RobotoMono Nerd Font"

[font]
size = 18.0

[colors]
  # Default colors
  primary = { background = '0x272822', foreground = '0xF8F8F2' }

  [colors.normal]
    black = '0x272822'
    red = '0xF92672'
    green = '0xA6E22E'
    yellow = '0xF4BF75'
    blue = '0x66D9EF'
    magenta = '0xAE81FF'
    cyan = '0xA1EFE4'
    white = '0xF8F8F2'

  [colors.bright]
    black = '0x272822'
    red = '0xF92672'
    green = '0xA6E22E'
    yellow = '0xF4BF75'
    blue = '0x66D9EF'
    magenta = '0xAE81FF'
    cyan = '0xA1EFE4'
    white = '0xF8F8F2'
