#!/bin/sh

# General stuff

alias \
		python=python3 \
		pip="python3 -m pip" \
		vim=nvim \
		tmux="tmux -f ~/.config/tmux/.tmux.conf"

# Settings that apparently I will always want
		
alias \
		cp="cp -iv" \
		mv="mv -iv" \
		bc="bc -ql" \
		mkd="mkdir -pv" \
		yt="youtube-dl --add-metadata -i" \
		yta="yt -x -f bestaudio/best" \
		ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	alias \
			ls="ls -hN --color=auto --group-directories-first" \
			grep="grep --color=auto" \
			diff="diff --color=auto" \
			ccat="highlight --out-format=ansi"
			rm="rm -vI" \
fi

# Git stuff

alias \
		g=git \
		gs="git status" \
		gr="git restore" \
		gp="git pull" \
		gc="git commit" \
		gd="git diff" \
		ga="git add" \
		gpa="git patch" \
		gpu="git push" \
		gcl="git clone"

