theme = "gruvbox"

[keys.normal]
g = { a = "code_action" }
A-p = "file_picker"
A-b = "buffer_picker"
S-k = "hover"
A-l = "jump_view_right"
A-h = "jump_view_left"
A-q = "wclose"
A-d = "half_page_down"
A-u = "half_page_up"
A-j = "page_down"
A-k = "page_up"
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"

[editor]
line-number = "relative"
cursorline = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.indent-guides]
render = true

[keys.normal."+"]
h = ["select_all", ":pipe xxd"]
r = ["select_all", ":pipe xxd -r"]

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"
