theme = "gruvbox"

[keys.normal]
g = { a = "code_action" }
C-p = "file_picker"
C-b = "buffer_picker"
S-k = "hover"

[editor]
line-number = "relative"
cursorline = true
rulers = [120]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.indent-guides]
render = true
