theme = "gruvbox"

[keys.normal]
g = { a = "code_action" }
C-p = "file_picker"
C-b = "buffer_picker"
S-k = "hover"
C-l = "jump_view_right"
C-h = "jump_view_left"
C-q = "wclose"
C-d = "half_page_down"
C-u = "half_page_up"
C-j = "page_down"
C-k = "page_up"
X = ["extend_line_up", "extend_to_line_bounds"]
C-x = "extend_to_line_bounds"
F5 = ":sh cargo r"

[editor]
line-number = "relative"
cursorline = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.indent-guides]
render = true

[keys.normal."+"]
h = ["select_all", ":pipe xxd"]
r = ["select_all", ":pipe xxd -r"]

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
C-x = "extend_to_line_bounds"

[editor.soft-wrap]
enable = true
