#!/bin/bash

git submodule update --remote

[ -f $HOME/.nvm/nvm.sh ] && echo "Nvm already exists" ||  mkdir ~/.nvm | curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
[ -f $HOME/.local/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh ] && echo "Fast Syntax Highlighting already cloned" || git clone https://github.com/zdharma-continuum/fast-syntax-highlighting $HOME/.local/share/zsh/plugins/fast-syntax-highlighting
[ -f $HOME/.local/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh ] && echo "Zsh Autosuggestions already cloned" || git clone https://github.com/zsh-users/zsh-autosuggestions.git $HOME/.local/share/zsh/plugins/zsh-autosuggestions
[ -d $HOME/.config/kitty/gruvbox ] && echo "Kitty Gruvbox already cloned" || git clone https://github.com/wdomitrz/kitty-gruvbox-theme.git $HOME/.config/kitty/gruvbox

set -e

# Ask the user if we can delete these?
[ -d $HOME/.config/nvim ] && echo "Nvim config detected" || git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

[ -f $HOME/.cargo/bin/rustc ] && echo "Rust already installed" || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

[ -f $CARGO_HOME/bin/exa ] && echo "Exa already installed" || cargo install exa | sh
[ -f $CARGO_HOME/bin/starship ] && echo "Starship already installed" || cargo install starship --locked | sh
[ -f $CARGO_HOME/bin/rg ] && echo "Ripgrep already installed" || cargo install ripgrep | sh
[ -f $CARGO_HOME/bin/bat ] && echo "Bat already installed" || cargo install bat | sh

nvim +PackerSync
