#!/bin/bash

git submodule update --remote

[ -f $HOME/.nvm/nvm.sh ] && echo "Nvm already exists" ||  mkdir ~/.nvm | curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

[ -f $HOME/.local/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh ] && echo "Fast Syntax Highlighting already cloned" || git clone https://github.com/zdharma-continuum/fast-syntax-highlighting $HOME/.local/share/zsh/plugins/fast-syntax-highlighting | bash

[ -f $HOME/.local/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh ] && echo "Zsh Autosuggestions already cloned" || git clone https://github.com/zsh-users/zsh-autosuggestions.git $HOME/.local/share/zsh/plugins/zsh-autosuggestions | bash

set -e

[ -d $HOME/.config/nvim ] && rm -rf ~/.config/nvim
[ -d $HOME/.local/share/nvim/site ] && rm -rf ~/.local/share/nvim/site
git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

[ -f $HOME/.cargo/bin/rustc ] && echo "Rust already installed" || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# cargo install exa
# cargo install starship --locked

nvim +PackerSync
