#!/bin/zsh

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch-config"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
export KODI_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/kodi"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"
export UNISON="${XDG_DATA_HOME:-$HOME/.local/share}/unison"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export WEECHAT_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/weechat"
export MBSYNCRC="${XDG_CONFIG_HOME:-$HOME/.config}/mbsync/config"
export ELECTRUMDIR="${XDG_DATA_HOME:-$HOME/.local/share}/electrum"

export LF_ICONS="di=ÃÂ°ÃÂÃÂÃÂ:\
fi=ÃÂ°ÃÂÃÂÃÂ:\
tw=ÃÂ°ÃÂÃÂ¤ÃÂ:\
ow=ÃÂ°ÃÂÃÂÃÂ:\
ln=Ã¢ÂÂ:\
or=Ã¢ÂÂ:\
ex=ÃÂ°ÃÂÃÂÃÂ¯:\
*.txt=Ã¢ÂÂ:\
*.mom=Ã¢ÂÂ:\
*.me=Ã¢ÂÂ:\
*.ms=Ã¢ÂÂ:\
*.png=ÃÂ°ÃÂÃÂÃÂ¼:\
*.webp=ÃÂ°ÃÂÃÂÃÂ¼:\
*.ico=ÃÂ°ÃÂÃÂÃÂ¼:\
*.jpg=ÃÂ°ÃÂÃÂÃÂ¸:\
*.jpe=ÃÂ°ÃÂÃÂÃÂ¸:\
*.jpeg=ÃÂ°ÃÂÃÂÃÂ¸:\
*.gif=ÃÂ°ÃÂÃÂÃÂ¼:\
*.svg=ÃÂ°ÃÂÃÂÃÂº:\
*.tif=ÃÂ°ÃÂÃÂÃÂ¼:\
*.tiff=ÃÂ°ÃÂÃÂÃÂ¼:\
*.xcf=ÃÂ°ÃÂÃÂÃÂ:\
*.html=ÃÂ°ÃÂÃÂÃÂ:\
*.xml=ÃÂ°ÃÂÃÂÃÂ°:\
*.gpg=ÃÂ°ÃÂÃÂÃÂ:\
*.css=ÃÂ°ÃÂÃÂÃÂ¨:\
*.pdf=ÃÂ°ÃÂÃÂÃÂ:\
*.djvu=ÃÂ°ÃÂÃÂÃÂ:\
*.epub=ÃÂ°ÃÂÃÂÃÂ:\
*.csv=ÃÂ°ÃÂÃÂÃÂ:\
*.xlsx=ÃÂ°ÃÂÃÂÃÂ:\
*.tex=ÃÂ°ÃÂÃÂÃÂ:\
*.md=ÃÂ°ÃÂÃÂÃÂ:\
*.r=ÃÂ°ÃÂÃÂÃÂ:\
*.R=ÃÂ°ÃÂÃÂÃÂ:\
*.rmd=ÃÂ°ÃÂÃÂÃÂ:\
*.Rmd=ÃÂ°ÃÂÃÂÃÂ:\
*.m=ÃÂ°ÃÂÃÂÃÂ:\
*.mp3=ÃÂ°ÃÂÃÂÃÂµ:\
*.opus=ÃÂ°ÃÂÃÂÃÂµ:\
*.ogg=ÃÂ°ÃÂÃÂÃÂµ:\
*.m4a=ÃÂ°ÃÂÃÂÃÂµ:\
*.flac=ÃÂ°ÃÂÃÂÃÂ¼:\
*.wav=ÃÂ°ÃÂÃÂÃÂ¼:\
*.mkv=ÃÂ°ÃÂÃÂÃÂ¥:\
*.mp4=ÃÂ°ÃÂÃÂÃÂ¥:\
*.webm=Ã¯ÂÂ½:\
*.mpeg=ÃÂ°ÃÂÃÂÃÂ¥:\
*.avi=ÃÂ°ÃÂÃÂÃÂ¥:\
*.mov=ÃÂ°ÃÂÃÂÃÂ¥:\
*.mpg=ÃÂ°ÃÂÃÂÃÂ¥:\
*.wmv=ÃÂ°ÃÂÃÂÃÂ¥:\
*.m4b=ÃÂ°ÃÂÃÂÃÂ¥:\
*.flv=ÃÂ°ÃÂÃÂÃÂ¥:\
*.zip=ÃÂ°ÃÂÃÂÃÂ¦:\
*.rar=ÃÂ°ÃÂÃÂÃÂ¦:\
*.7z=ÃÂ°ÃÂÃÂÃÂ¦:\
*.tar.gz=ÃÂ°ÃÂÃÂÃÂ¦:\
*.z64=ÃÂ°ÃÂÃÂÃÂ®:\
*.v64=ÃÂ°ÃÂÃÂÃÂ®:\
*.n64=ÃÂ°ÃÂÃÂÃÂ®:\
*.gba=ÃÂ°ÃÂÃÂÃÂ®:\
*.nes=ÃÂ°ÃÂÃÂÃÂ®:\
*.gdi=ÃÂ°ÃÂÃÂÃÂ®:\
*.1=Ã¢ÂÂ¹:\
*.nfo=Ã¢ÂÂ¹:\
*.info=Ã¢ÂÂ¹:\
*.log=ÃÂ°ÃÂÃÂÃÂ:\
*.iso=ÃÂ°ÃÂÃÂÃÂ:\
*.img=ÃÂ°ÃÂÃÂÃÂ:\
*.bib=ÃÂ°ÃÂÃÂÃÂ:\
*.ged=ÃÂ°ÃÂÃÂÃÂª:\
*.part=ÃÂ°ÃÂÃÂÃÂ:\
*.torrent=ÃÂ°ÃÂÃÂÃÂ½:\
*.jar=Ã¢ÂÂ¨:\
*.java=Ã¢ÂÂ¨:\
"

eval "$(/opt/homebrew/bin/brew shellenv)"


